<?php
require_once '../../includes/auth.php';
requireLogin();

$projectId = $_GET['id'] ?? 0;

if (!$projectId) {
    header('Location: /PMS/modules/admin/projects.php');
    exit;
}

// Get project details
$db = Database::getInstance();
$stmt = $db->prepare("SELECT p.*, c.name as client_name FROM projects p LEFT JOIN clients c ON p.client_id = c.id WHERE p.id = ?");
$stmt->execute([$projectId]);
$project = $stmt->fetch();

if (!$project) {
    header('Location: /PMS/modules/admin/projects.php');
    exit;
}

// Fetch issue statuses
$statusesStmt = $db->query("SELECT id, name as status_name, color, category FROM issue_statuses ORDER BY name ASC");
$issueStatuses = $statusesStmt->fetchAll(PDO::FETCH_ASSOC);

$page_title = 'Issues - React Version';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($page_title); ?> - <?php echo htmlspecialchars($project['title']); ?></title>
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="/PMS/assets/css/style.css">
    
    <style>
        body {
            background-color: #f8f9fa;
        }
        #root {
            min-height: 100vh;
        }
        .react-loading {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
    </style>
</head>
<body>
    <!-- React App Root -->
    <div id="root">
        <div class="react-loading">
            <div class="text-center">
                <div class="spinner-border text-primary" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
                <p class="mt-3 text-muted">Loading React App...</p>
            </div>
        </div>
    </div>

    <!-- Pass PHP data to React -->
    <script>
        window.APP_CONFIG = {
            projectId: <?php echo (int)$projectId; ?>,
            projectTitle: <?php echo json_encode($project['title']); ?>,
            projectType: <?php echo json_encode($project['project_type']); ?>,
            userId: <?php echo (int)$_SESSION['user_id']; ?>,
            userName: <?php echo json_encode($_SESSION['full_name'] ?? $_SESSION['username']); ?>,
            userRole: <?php echo json_encode($_SESSION['role']); ?>,
            apiBase: '/PMS/api',
            baseUrl: window.location.origin,
            issueStatuses: <?php echo json_encode($issueStatuses); ?>
        };
    </script>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
    <!-- React App Bundle (will be generated by Vite) -->
    <script type="module" src="/PMS/modules/react/issues-app/dist/assets/index.js"></script>
</body>
</html>
